AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  survey-api-java

  Sample SAM Template for survey-api-java

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables:
        SURVEYS_TABLE: !Ref SurveysTable

Resources:
  SurveysTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: survey_id
        Type: Number
  CreateSurveyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: survey-api
      Handler: com.surveyapi.lambdahandlers.CreateSurveyHandler::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SurveysTable
      Events:
        SurveyEvents:
          Type: Api
          Properties:
            Path: /surveys
            Method: POST
  ReadSurveysFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: survey-api
      Handler: com.surveyapi.lambdahandlers.ReadSurveysHandler::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SurveysTable
      Events:
        SurveyEvents:
          Type: Api
          Properties:
            Path: /surveys
            Method: GET

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SurveyApi:
    Description: "API Gateway endpoint URL for Prod stage for Survey APIs"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/surveys/"
  CreateSurveyFunction:
    Description: "Create Survey Lambda Function ARN"
    Value: !GetAtt CreateSurveyFunction.Arn
  CreateSurveyFunctionIamRole:
    Description: "Implicit IAM Role created for Create Survey function"
    Value: !GetAtt CreateSurveyFunctionRole.Arn
